### ISSUE TITLE
Nothing written to generated file

### ISSUE THREAD

**Issue by JimTompkins** [delay/getx_google_sheets_translation_code_generator#1]
First, thanks for your Medium article and for this code generator!

I tried it and there is nothing in the localization.g.dart file.  I uncommented line 37

    print('Google sheet csv:\n ${response.body}');

and it seems to be printing an html file, not csv.

I also added a print statement inside the     for (var r = 1; r < fields.length; r++) {
 loop and it doesn't print anything.

Did something change in the way Google sheets downloads a .csv file?

Thanks,

Jim

**Comment by JimTompkins** [comment]
I found that changing line 32 to:

        'https://docs.google.com/spreadsheets/d/$documentId/export?format=csv&id=$documentId&gid=$sheetId';

works.

Also, you need to escape single quotes e.g. can't should be can\'t

**Comment by delay** [comment]
Thank you for this info...  Thanks so much for reporting this bug!  Good luck with your project!
